// GENERATED by build/make-assets.py — 手で編集しないこと。
// 原本は ../../source/。差し替えたらこのスクリプトを再実行する。
window.ASSETS = {
 "chara": {
  "chara_maou_a": {
   "src": "assets/chara/chara_maou_a.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_maou_b": {
   "src": "assets/chara/chara_maou_b.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_maou_c": {
   "src": "assets/chara/chara_maou_c.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_maou_d": {
   "src": "assets/chara/chara_maou_d.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_norman_a": {
   "src": "assets/chara/chara_norman_a.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_norman_b": {
   "src": "assets/chara/chara_norman_b.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_norman_c": {
   "src": "assets/chara/chara_norman_c.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_norman_d": {
   "src": "assets/chara/chara_norman_d.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_falm_a": {
   "src": "assets/chara/chara_falm_a.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_falm_b": {
   "src": "assets/chara/chara_falm_b.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_falm_c": {
   "src": "assets/chara/chara_falm_c.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_kanban_a": {
   "src": "assets/chara/chara_kanban_a.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_kanban_b": {
   "src": "assets/chara/chara_kanban_b.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_kanban_c": {
   "src": "assets/chara/chara_kanban_c.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_tact_a": {
   "src": "assets/chara/chara_tact_a.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_tact_b": {
   "src": "assets/chara/chara_tact_b.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  },
  "chara_tact_c": {
   "src": "assets/chara/chara_tact_c.webp?v=202609011237",
   "w": 838,
   "h": 900,
   "transparent": true
  }
 },
 "koma": {
  "koma_01_tenraku": {
   "src": "assets/koma/koma_01_tenraku.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_02_1_suite": {
   "src": "assets/koma/koma_02_1_suite.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_02_2_sakaba": {
   "src": "assets/koma/koma_02_2_sakaba.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_02_3_kohan": {
   "src": "assets/koma/koma_02_3_kohan.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_02_4_odori": {
   "src": "assets/koma/koma_02_4_odori.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_02_5_enkai": {
   "src": "assets/koma/koma_02_5_enkai.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_03_1_sashimodoshi": {
   "src": "assets/koma/koma_03_1_sashimodoshi.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_03_2_sashimodoshi": {
   "src": "assets/koma/koma_03_2_sashimodoshi.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_03_3_sashimodoshi": {
   "src": "assets/koma/koma_03_3_sashimodoshi.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_03_4_sashimodoshi": {
   "src": "assets/koma/koma_03_4_sashimodoshi.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_03_5_settai": {
   "src": "assets/koma/koma_03_5_settai.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_04_shotaibare": {
   "src": "assets/koma/koma_04_shotaibare.webp?v=202609011237",
   "w": 1280,
   "h": 853
  },
  "koma_05_epilogue": {
   "src": "assets/koma/koma_05_epilogue.webp?v=202609011237",
   "w": 853,
   "h": 1280
  }
 },
 "bg": {
  "bg_shinsa_01": {
   "src": "assets/bg/bg_shinsa_01.webp?v=202609011237",
   "w": 2400,
   "h": 1350
  },
  "still_village_01": {
   "src": "assets/bg/still_village_01.webp?v=202609011237",
   "w": 1600,
   "h": 900
  },
  "still_throne_01": {
   "src": "assets/bg/still_throne_01.webp?v=202609011237",
   "w": 1600,
   "h": 900
  },
  "still_gate_dusk_01": {
   "src": "assets/bg/still_gate_dusk_01.webp?v=202609011237",
   "w": 1600,
   "h": 900
  },
  "still_maou_sleep_01": {
   "src": "assets/bg/still_maou_sleep_01.webp?v=202609011237",
   "w": 1600,
   "h": 900
  },
  "still_maou_wake_01": {
   "src": "assets/bg/still_maou_wake_01.webp?v=202609011237",
   "w": 1600,
   "h": 900
  },
  "title_key_b": {
   "src": "assets/bg/title_key_b.webp?v=202609011237",
   "w": 1600,
   "h": 900
  },
  "title_key_b_portrait_v2": {
   "src": "assets/bg/title_key_b_portrait_v2.webp?v=202609011237",
   "w": 1024,
   "h": 2216
  }
 },
 "map": {
  "map_castle_01": {
   "src": "assets/dot/map_castle_01.png?v=202609011237",
   "w": 480,
   "h": 320
  }
 },
 "dot": {
  "dot_falm_sheet": {
   "src": "assets/dot/dot_falm_sheet.png?v=202609011237",
   "w": 128,
   "h": 32,
   "frames": 4
  },
  "dot_kanban_sheet": {
   "src": "assets/dot/dot_kanban_sheet.png?v=202609011237",
   "w": 128,
   "h": 32,
   "frames": 4
  },
  "dot_maou_sheet": {
   "src": "assets/dot/dot_maou_sheet.png?v=202609011237",
   "w": 256,
   "h": 32,
   "frames": 8
  },
  "dot_norman_sheet": {
   "src": "assets/dot/dot_norman_sheet.png?v=202609011237",
   "w": 128,
   "h": 32,
   "frames": 4
  },
  "dot_tact_sheet": {
   "src": "assets/dot/dot_tact_sheet.png?v=202609011237",
   "w": 128,
   "h": 32,
   "frames": 4
  }
 },
 "ui": {
  "ui_paper_01": {
   "src": "assets/ui/ui_paper_01.webp?v=202609011237",
   "w": 512,
   "h": 512,
   "magenta": false
  },
  "ui_stamp_reject_01": {
   "src": "assets/ui/ui_stamp_reject_01.webp?v=202609011237",
   "w": 512,
   "h": 512,
   "magenta": false
  },
  "ui_stamp_approve_01": {
   "src": "assets/ui/ui_stamp_approve_01.webp?v=202609011237",
   "w": 512,
   "h": 512,
   "magenta": false
  },
  "ui_stomach_01": {
   "src": "assets/ui/ui_stomach_01.png?v=202609011237",
   "w": 96,
   "h": 32,
   "magenta": false
  },
  "ui_title_logo_01": {
   "src": "assets/ui/ui_title_logo_01.webp?v=202609011237",
   "w": 1400,
   "h": 525,
   "magenta": false
  }
 },
 "bgm": {
  "bgm_opening_01": {
   "src": "assets/audio/bgm_opening_01.mp3?v=202609011237"
  },
  "bgm_throne_01": {
   "src": "assets/audio/bgm_throne_01.mp3?v=202609011237"
  },
  "bgm_shinsa_01": {
   "src": "assets/audio/bgm_shinsa_01.mp3?v=202609011237"
  },
  "bgm_shinmiri_01": {
   "src": "assets/audio/bgm_shinmiri_01.mp3?v=202609011237"
  },
  "bgm_field_01": {
   "src": "assets/audio/bgm_field_01.mp3?v=202609011237"
  },
  "bgm_rush_01": {
   "src": "assets/audio/bgm_rush_01.mp3?v=202609011237"
  },
  "bgm_boss_01": {
   "src": "assets/audio/bgm_boss_01.mp3?v=202609011237"
  },
  "bgm_tohoho_01": {
   "src": "assets/audio/bgm_tohoho_01.mp3?v=202609011237"
  }
 },
 "se": {
  "se_slam_01": {
   "src": "assets/audio/se_slam_01.mp3?v=202609011237"
  },
  "se_boom_01": {
   "src": "assets/audio/se_boom_01.mp3?v=202609011237"
  },
  "se_hit_01": {
   "src": "assets/audio/se_hit_01.mp3?v=202609011237"
  },
  "se_stamp_reject_01": {
   "src": "assets/audio/se_stamp_reject_01.mp3?v=202609011237"
  },
  "se_stamp_ok_01": {
   "src": "assets/audio/se_stamp_ok_01.mp3?v=202609011237"
  }
 }
};
window.ASSET_STATE = {
 "charaTransparent": true,
 "charaTransparentIds": [
  "chara_maou_a",
  "chara_maou_b",
  "chara_maou_c",
  "chara_maou_d",
  "chara_norman_a",
  "chara_norman_b",
  "chara_norman_c",
  "chara_norman_d",
  "chara_falm_a",
  "chara_falm_b",
  "chara_falm_c",
  "chara_kanban_a",
  "chara_kanban_b",
  "chara_kanban_c",
  "chara_tact_a",
  "chara_tact_b",
  "chara_tact_c"
 ],
 "charaSource": {
  "chara_maou_a": "transparent",
  "chara_maou_b": "transparent",
  "chara_maou_c": "transparent",
  "chara_maou_d": "transparent",
  "chara_norman_a": "transparent",
  "chara_norman_b": "transparent",
  "chara_norman_c": "transparent",
  "chara_norman_d": "transparent",
  "chara_falm_a": "transparent",
  "chara_falm_b": "transparent",
  "chara_falm_c": "transparent",
  "chara_kanban_a": "transparent",
  "chara_kanban_b": "transparent",
  "chara_kanban_c": "transparent",
  "chara_tact_a": "transparent",
  "chara_tact_b": "transparent",
  "chara_tact_c": "transparent"
 },
 "dotMagenta": false,
 "uiMagenta": {
  "ui_paper_01": false,
  "ui_stamp_reject_01": false,
  "ui_stamp_approve_01": false,
  "ui_stomach_01": false,
  "ui_title_logo_01": false
 },
 "bgmReady": [
  "bgm_opening_01",
  "bgm_throne_01",
  "bgm_shinsa_01",
  "bgm_shinmiri_01",
  "bgm_field_01",
  "bgm_rush_01",
  "bgm_boss_01",
  "bgm_tohoho_01"
 ],
 "bgmMissing": [],
 "seFiles": [
  "se_slam_01",
  "se_boom_01",
  "se_hit_01",
  "se_stamp_reject_01",
  "se_stamp_ok_01"
 ],
 "seSynth": [
  "se_door_open_01",
  "se_papers_drop_01",
  "se_glasses_01",
  "se_glasses_off_01",
  "se_tap_align_01",
  "se_gulp_01",
  "se_flash_01",
  "se_step_01",
  "se_item_01",
  "se_ui_select_01"
 ],
 "totalBytes": 21249244
};
