// GENERATED by build/parse.js — 手で編集しないこと。本文の正は ../../02_scenario.md
// 生成日時: 2026-09-01T03:22:09.471Z
window.SCENES = [
 {
  "id": "S0",
  "title": "冒頭シリアス",
  "nodes": [
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／一枚絵①：村を発つ勇者一行",
    "tags": [
     "tone:serious",
     "明朝体",
     "暗色トーン",
     "テキスト送り:遅",
     "BGM:荘厳"
    ]
   },
   {
    "t": "line",
    "who": "narration",
    "name": "ナレーション",
    "text": "魔物が地を這い、空を裂き、人の営みを削り取る時代。",
    "tags": [],
    "mono": false
   },
   {
    "t": "line",
    "who": "narration",
    "name": "ナレーション",
    "text": "人々は、ただ一人の英雄を待っていた。",
    "tags": [],
    "mono": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "行こう、みんな。世界の命運は、俺たちの肩にかかっている",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……ああ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "（また始まった）",
    "tags": [
     "心の声表示"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "……",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "narration",
    "name": "ナレーション",
    "text": "勇者ノルマン。人々の希望を背負い、彼は魔の座す城へと向かう。",
    "tags": [],
    "mono": false
   },
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／一枚絵②：魔王城・玉座の間",
    "tags": [
     "暗転→明転",
     "BGM:重厚"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "よくぞ来た、勇者よ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "幾千の夜を越え、幾万の骸を踏み、貴様はここへ辿り着いた",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "その旅路——この魔王が、直々に裁定してくれよう",
    "tags": [
     "BGM:最高潮",
     "ズームイン"
    ],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S1",
  "title": "転落の瞬間",
  "nodes": [
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#1",
     "BGM:ぶつ切り",
     "明転",
     "tone:gag",
     "ゴシック体",
     "テキスト送り:速"
    ]
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あ、すみませーん。精算お願いしまーす",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／魔王城マップ",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……は？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（伝票の束をドサッ）今月分です！",
    "tags": [
     "sfx:ドサァ",
     "shake"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "…………",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "（老眼鏡をかける）",
    "tags": [
     "sfx:カチャ"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "先に言っておく。今日は、そういう日ではない",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "いや今月中に締めないと、次の遠征費おりないんで",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S2",
  "title": "制度説明・タイトルコール・審査ルール",
  "nodes": [
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "背景:審査の間",
     "BGM:事務的なのに緊迫"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "勇者活動支援制度。魔王国が、勇者の旅費を負担する制度だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "討伐で村や道を壊されるより、金を出して行動を管理したほうが安い",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あざっす！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……疑問に思わんのか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え、なにがですか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "私は、貴様が倒しに来ている相手だぞ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……あ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "この戦いは、興行だ。客がいて、席が埋まり、木戸銭が入る",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "打っているのは、我が魔王国。つまり——主催は、私だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "主催が旅費を持つ。貴様が旅で使っている金は、私の金だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "へえ〜",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "だから私は、一枚ずつ見る",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "で、次の遠征費は出るんですか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……いま、その話をしていた",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "そうそう、補助金出るってやつ！　サインしました！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "契約書は読んだか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "読んでないっす！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "タイトルコール",
    "note": "",
    "tags": [
     "大書き文字",
     "tone:gag"
    ]
   },
   {
    "t": "titlecall"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "次の遠征費と、聖剣の強化許可。どちらも前回分の精算承認が条件だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "つまり——この5枚を私が通さん限り、貴様は一歩も進めん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "今回は絶対通りますから！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "その台詞、何度目だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "チュートリアル説明（胃ゲージ）",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "ひとつ言っておく。私は、判断を誤ると胃が痛む",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "3回痛めば、私は全部承認して寝る",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "そうなれば、貴様の不正はすべて通る。……覚えておけ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え、じゃあ3回間違えてくださいよ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "差し戻し",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "まだ何も出してない！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "チュートリアル説明（呼び出し）",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "もうひとつ。審査中、私はあの3人を証人として呼ぶ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "俺の仲間ですよ！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "ならば、やましいことはあるまい",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "（遠くから）呼ばれたら、全部話すぞ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "仲間ぁ！？",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S3",
  "title": "伝票1：宿泊費（豪華な部屋とルームサービス）＝部分承認の教え",
  "nodes": [
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "まずは宿泊費。ハーメルンの宿、一泊**8,000ゴールド**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……8,000",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "同じ宿の標準室は、**800**だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "空いてなかったんですよ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "言い逃れ・第1段：満室主張",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "ほう。繁忙期だったか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "そうそう！　収穫祭で、町中が満室で！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "何の収穫だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……芋？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**なぜ疑問形だ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼呼び出し：カンバンの証言"
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "当日の空室記録です。標準室、**11室空いていました**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "カンバン",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "記録は、残るので",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "「11室」の畳みかけ",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "じゅ、11室って、ほぼ全部じゃ……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "標準室は、全12室です",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "埋まっていた1室は、**あなたの隣の部屋**です",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "（遠くから）俺だ。**うるさかったぞ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "話が早い！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……続けて聞く。この『室内飲食代 3,200』は",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "ルームサービスです。遠征で疲れてたんで",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**深夜2時に、肉を4皿**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "4皿は疲れてる証拠でしょ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "言い逃れ・第2段：正当化芸",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "じゃあ言いますけど、あれは**みんなの分**です！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "部屋は、一人用だが",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "差し入れです！　俺から、俺への！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "品目——**『祝勝肉盛り　勇者スペシャル』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……頼んじゃった",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**何に勝った**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "まだ、何も",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼プレイヤー判断：承認／差し戻し"
   },
   {
    "t": "dir",
    "raw": "正解：差し戻し　根拠：カンバンの空室記録"
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#3-1",
     "集中線",
     "shake",
     "sfx:ドンッ"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し！**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "勘違いするな。**宿泊そのものは業務だ。標準室の800は通す**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え、通るんですか！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "通る。**業務に必要な費用を、私は削らん**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "だが——**差額の7,200と、深夜の肉4皿は、貴様の趣味だ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……趣味ではある",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "部分承認の教え・追い1往復",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……ちなみに、来月から標準室に泊まったら",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "800、全額通す",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え、毎回ちゃんと出るんだ……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**制度とは、そういうものだ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "（メモ）来月から標準室、と",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "書き留めるの早くない！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#2-1／やらかし回想",
     "モノクロ",
     "粗線",
     "tone:回想"
    ]
   },
   {
    "t": "narr",
    "text": "回想：宿の最上級スイート。天蓋付きベッドに大の字のノルマン。床には皿の山。",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）いやー、勇者やってると疲れるわー",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）すいませーん、肉もう一皿！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "（回想・隣室から壁越しに）**うるせえぞ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "tone:gag"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "1枚目から、これか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "まだ4枚ありますよ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "脅しか",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S3b",
  "title": "幕間A：城内うろつき①（v2.0新設・裁定M）",
  "nodes": [
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／ドット絵・魔王城マップ",
    "tags": [
     "操作:魔王のみ4方向",
     "NPC:左右自動うろうろ",
     "BGM:のんびり",
     "tone:gag"
    ]
   },
   {
    "t": "dir",
    "raw": "▼進行：自由行動。話しかけは任意（誰とも話さなくても進行可＝詰みなし）。審査の間の机を調べると確認ダイアログ→S4へ。"
   },
   {
    "t": "dir",
    "raw": "▼ヒント：カンバンと話すと hint_kanban=true（伝票2の証言の種＝在庫記録の存在の予告）。"
   },
   {
    "t": "dir",
    "raw": "▼自動セーブ復帰点：本シーン頭。"
   },
   {
    "t": "mark",
    "label": "僧侶カンバンに話しかけた場合",
    "note": "",
    "tags": [
     "hint_kanban=true"
    ]
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "魔王様。ひとつ、ご報告が",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "私、パーティの**消耗品の在庫記録**をつけています",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……ほう",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "回復薬の出入りも、**1本単位で**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……それは、次の審査で聞くことになりそうだ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "いつでも、お呼びください",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "戦士タクトに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "魔王城って、あったかいんだな。もっと溶岩とかあるのかと",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "暖房は経費で入れている。溶岩は燃費が悪い",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "燃費で溶岩やめた魔王城……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "そういや、次の巡……討伐の日程なんだがな",
    "tags": [
     "※秘密A・v2.0増補分の匂わせ（発注書の上限1箇所）"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……今、何と言いかけた",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "討伐の日程だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……まあ、いい",
    "tags": [
     "※秘密A：魔王がここで打ち切る"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "（目をそらして口笛）",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "賢者ファルムに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "詠唱の仕様書を書いています。あの男が読まないので",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "読まんだろうな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "読まれない仕様書を書き続ける仕事、前世でもやっていました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "**動いているものに触るな**。詠唱も組み込みも、鉄則は同じです",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……いい鉄則だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "勇者ノルマンに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "まだですかー？　俺、次の遠征あるんですけど",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "精算が終われば、な",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（自分の伝票の束を見る）……結構あるなあ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**貴様の枚数だ**",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S4",
  "title": "伝票2：酒場「金の孔雀亭」指名料 ／ 三段開示・第1段階（疑念の芽）",
  "nodes": [
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "次、回復薬の補充費。**90本**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "90本",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……ちょうど、90か",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "魔王の独白",
    "note": "",
    "tags": [
     "tone:serious",
     "明朝体",
     "テキスト送り:遅",
     "BGM:一瞬止まる"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……この数字の丸め方",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "実数を書かず、切りのいい数へ寄せる癖",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "どこかで、見たことがある",
    "tags": [
     "無言ビート"
    ],
    "mono": true
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "tone:gag",
     "BGM:復帰"
    ]
   },
   {
    "t": "dir",
    "raw": "▼呼び出し：カンバンの証言"
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "在庫記録では、消費されたのは**12本**です",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "日付・出庫時刻・担当者、すべて控えてあります",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "カンバン、そういうとこだぞ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "そういうところで生きてきましたので",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……では、残りの78本分の金は、どこへ行った",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……この添付、なんだ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『金の孔雀亭　ご指名料　同伴料　場内指名』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あー！　それは！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "情報収集です！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "情報収集",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "酒場には情報が集まるでしょ！？　RPGの基本！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "言い逃れ・第2段：成果発表会",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "では、何を集めた",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "情報収集と言ったな。**成果物を出せ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……ミナちゃんの誕生日が、先週",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あと、店長さんは猫を3匹飼ってて",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**魔王国の軍事に関わる情報は**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "ないです",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**基本は、自腹だ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼プレイヤー判断：差し戻し　根拠：カンバンの在庫記録（回復薬名目の実費が合わない）"
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#3-2",
     "集中線",
     "sfx:ドンッ"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し！**　業務と関係のない遊興費は、1ゴールドも通さん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#2-2／やらかし回想",
     "モノクロ",
     "粗線"
    ]
   },
   {
    "t": "narr",
    "text": "回想：酒場「金の孔雀亭」。両手に花で上機嫌のノルマン。",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）いやー、俺いま世界救ってましてー",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "extra",
    "name": "コンパニオン",
    "text": "（回想）すごーい！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）**これ、経費で落ちるんで**！　もう一本入れて！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "（回想・入口から）……落ちませんよ、それは",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）落ちる落ちる",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "落ちん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "落ちないっすか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "落ちん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "答え合わせ",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "ちなみに、伝票の日付ですが",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "**ミナさんの誕生日、当日です**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……情報収集ではなく、**祝いに行っただけか**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "シャンパン、入れました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**それは貢ぎ物という**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "なお店長の猫は、**4匹に増えていた**そうです",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**情報が古い**",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S5",
  "title": "伝票3：討伐に伴う損害弁償 ／ 承認が正解の伝票・疑念が確信へ",
  "nodes": [
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "BGM:少ししんみり"
    ]
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……次のやつ、あの",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "たぶんダメだと思うんですけど、一応",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "出せ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "**メルドの村の、水車小屋の弁償金。46,000**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "討伐の時に、オークを吹き飛ばしたら、その先に小屋があって",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……村の人には、謝りました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "あれは避けられん。俺も見てた",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "討伐日報にも、記録があります",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "もう1件：仲間の損害",
    "note": "",
    "tags": [
     "tone:serious寄り"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……この伝票、もう1件ある",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『メルドの村　看板　修理費　9,000』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……それは、俺だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "オークを組み伏せた時に、一緒に倒した",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**それは、俺が払う**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**現場のミスは、現場が被る**。前の会社では、そうだった",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート",
     "BGM:止まる"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**ならん**",
    "tags": [
     "tone:serious",
     "明朝体"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "は",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**討伐中の損害だ。会社が払う**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "貴様は業務をしていた。**業務でついた傷を、個人に払わせる制度ではない**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**ここは、そうではない**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "…………",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……**そういう会社が、あったんだな**",
    "tags": [
     "小さく"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "魔王の独白（職業芸の披露）",
    "note": "",
    "tags": [
     "tone:serious",
     "明朝体",
     "テキスト送り:遅"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……この領収書の貼り方",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "斜め45度。糊は角だけ。ホチキスは右上を、二回打ち",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……間違いない",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "私はこの貼り方を、20年見てきた",
    "tags": [
     "無言ビート"
    ],
    "mono": true
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "dir",
    "raw": "▼プレイヤー判断：承認／差し戻し"
   },
   {
    "t": "dir",
    "raw": "正解：承認　（業務遂行上やむを得ない損害）"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**2件とも、承認する**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え、いいんですか！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**業務上やむを得ない損害は、会社が払う**。当たり前だ",
    "tags": [
     "tone:serious"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "討伐は業務だ。避けられん被害まで、個人に背負わせる制度ではない",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**それは勇者だろうと、仲間だろうと同じだ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……ありがたい",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**私は、意地悪をしているのではない**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**通すべきものは、通す**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……ありがとうございます",
    "tags": [
     "素直",
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "tone:gag",
     "BGM:元に戻る"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "その代わり、残りは全部差し戻す",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "話が違う！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "話は違わん。**中身が違う**",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S5b",
  "title": "幕間B：城内うろつき②（v2.0新設・裁定M）",
  "nodes": [
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／ドット絵・魔王城マップ",
    "tags": [
     "操作:魔王のみ4方向",
     "NPC:左右自動うろうろ",
     "BGM:のんびり",
     "tone:gag"
    ]
   },
   {
    "t": "dir",
    "raw": "▼進行：自由行動。話しかけは任意（詰みなし）。審査の間の机を調べると確認ダイアログ→S6へ。"
   },
   {
    "t": "dir",
    "raw": "▼ヒント：ファルムと話すと hint_falm=true（伝票4の証言の種）。「仕様変更」の語は出さない（相互認知の先バレ禁止・発注書指定）。"
   },
   {
    "t": "dir",
    "raw": "▼自動セーブ復帰点：本シーン頭。"
   },
   {
    "t": "mark",
    "label": "戦士タクトに話しかけた場合",
    "note": "（S5の余韻→ギャグで回収）",
    "tags": []
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……なあ。さっきの、看板の",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "決裁は済んだ。もう言うな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**業務の傷は、会社が払う**……",
    "tags": [
     "噛みしめている"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "当然のことをしたまでだ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……なあ、魔王様。**魔王軍って、求人あるか**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**敵だぞ、貴様は**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "そうだった",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "賢者ファルムに話しかけた場合",
    "note": "",
    "tags": [
     "hint_falm=true"
    ]
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "魔王様。次は、聖剣の強化費ですね",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……なぜ知っている",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "机の伝票、**はみ出して見えていました**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "**聖剣の話は、私に聞いてください**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……含みのある言い方だな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "**審査の場で、申し上げます**",
    "tags": [
     "目が据わっている"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "僧侶カンバンに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "魔王様。これを",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……胃薬か",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "審査は、まだ残っていますので",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……もらっておく",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "前世で、**上司によく渡していました**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……いい部下を持ったな、その上司は",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "勇者ノルマンに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……水車小屋の、ほんとに通ったんですね",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（小声）ちゃんとしてれば、通るのか……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "聞こえているぞ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "じゃ、次のも頼みますよ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**中身によるな**",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S6",
  "title": "伝票4：聖剣強化費と建物損壊 ／ 三段開示・第2段階（相互認知）",
  "nodes": [
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "聖剣の強化費。これは絶対に必要です！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "聖剣は、魔王国からの貸与品だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "減価償却も、こちら持ちだぞ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "じゃあ強化もそっち持ちで",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "ならん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "押し問答・増段",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "世界を救う剣ですよ！？　投資でしょ、投資！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "投資には、回収計画書が要る",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "世界が平和になります！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**数字で出せ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……ぷ、プライスレス？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**プライスレスは、経理が最も嫌う言葉だ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "そもそも減価償却って、なんすか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**知らずに頷いていたのか、貴様は**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "経理っぽい人が言うと、なんか通るかなって",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "通らん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "てか、なんで魔王が回収計画書とか知ってるんすか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "話を戻す",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……それと、この添付",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『ハーメルン中央通り　建物3棟　修繕費　82万』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あー、それはですね",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "**聖剣の、本気の威力を、みんなに見せようと思って**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "敵は",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "**いなかったです**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼呼び出し：ファルムの証言"
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "……その件ですが",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "営業が、**勝手に、仕様変更しました**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "ファルム！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "出力上限のリミッターを外せと。納期は翌日",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "設計は私です。三日、寝ていません",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "**外した結果が、通り3本です**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "BGM:停止",
     "無言ビート",
     "tone:serious",
     "明朝体"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……今、なんと言った",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "営業が、勝手に、仕様変更を",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "beat",
    "tags": [
     "flash",
     "記憶のフラッシュバック演出"
    ],
    "text": ""
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "雑な精算",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "丸めた数字",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "斜めに貼られた領収書",
    "tags": [],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "——勝手な、仕様変更",
    "tags": [
     "shake"
    ],
    "mono": true
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……お前",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "お前、もしかして——**田中**か？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……その差し戻し方",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "もしかして……**経理の**……？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#4／正体バレ",
     "flash",
     "書き文字:ガーン",
     "ズーム"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**勇者ノルマン殿……いや、田中**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "か——**課長**ォ！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "tone:gag",
     "BGM:コミカルに復帰"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "転生してまで、私に精算をさせに来たのか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "いやこれは偶然で",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "偶然の精度が高すぎる",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼プレイヤー判断：差し戻し　根拠：ファルムの証言（申請外の仕様変更・敵不在）"
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#3-4",
     "集中線",
     "sfx:ドンッ"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し！**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**敵のいない場所で振った剣の損害は、業務ではない。見栄だ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "田中。さっきの水車小屋は通した",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "戦って、やむを得ず壊したからだ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**だがこれは、誰とも戦っていない**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……はい",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "前世でも、貴様は同じことをした",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "勝手に約束し、勝手に納期を決め、精算だけは遅い",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……覚えてます？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "20年、覚えている",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#2-4／やらかし回想",
     "モノクロ",
     "粗線"
    ]
   },
   {
    "t": "narr",
    "text": "回想：目抜き通り。聖剣を掲げるノルマンと、背後で崩れていく建物3棟。歓声を上げる群衆。",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）見とけよー！　これが勇者の力だ！",
    "tags": [
     "ドヤ顔"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "extra",
    "name": "群衆",
    "text": "（回想）うおおおお！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "（回想・徹夜明けの顔で遠くから）……リミッター、外した意味",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "tone:gag"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……歓声は、金にならん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "なりませんでした",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "拍手は、無料ですので",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**82万の拍手だったな**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……高い拍手だ",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S7",
  "title": "幕間：城内うろつき ／ 三段開示・第3段階（連鎖発覚）",
  "nodes": [
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／ドット絵・魔王城マップ",
    "tags": [
     "操作:魔王のみ4方向",
     "NPC:左右自動うろうろ",
     "BGM:のんびり"
    ]
   },
   {
    "t": "dir",
    "raw": "▼操作説明：魔王を歩かせ、仲間3人に話しかける（3人全員に話しかけると次へ進む）"
   },
   {
    "t": "mark",
    "label": "戦士タクトに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……田中？　今、田中って言ったか？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "試作品を、そのまま量産ラインにねじ込んだ、あの田中か！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "俺は3ヶ月、現場で謝り続けたんだぞ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "展示会の試作品を、客の前で**『もう量産してます』**と言いやがった",
    "tags": [
     "v2.0増補"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "ラインを止めて、**30台、手で組んだ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "あの3日間、俺は工具としか会話してない",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（遠くから）人違いでーす",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**お前、田中かよ！**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "僧侶カンバンに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "……納期は昨日、と",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "今朝、言われました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "彼の『できました』は、**『着手しました』の意味**です",
    "tags": [
     "v2.0増補"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "その翻訳に、3年かかりました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "私は、その日から数字を信じるのをやめました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "……ノルマン。いえ、**田中**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "賢者ファルムに話しかけた場合",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "魔王様。ひとつ確認させてください",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "あなたが、あの経理課長ですか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……そうだ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "では、私の残業申請は",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……前世の分は、時効だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "時効は、ありません",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "……ついでに、あの男の話も",
    "tags": [
     "v2.0増補"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "聞こう",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "**『デモで一回動けばいい』**と言われて書いた詠唱が",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "**10年、現役で動いています**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "直せません。**動いているので**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "3人全員と話した後（自動発生）",
    "note": "",
    "tags": [
     "全員集合",
     "shake"
    ]
   },
   {
    "t": "line",
    "who": "trio",
    "name": "タクト・カンバン・ファルム",
    "text": "**お前、田中かよ！**",
    "tags": [
     "3人同時",
     "sfx:ドンッ"
    ],
    "mono": false,
    "group": true
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "なんでみんな俺の前世知ってんの！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**お前がやったんだよ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……被害者の会が、勝手に結成されているな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "会費は無料です",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "入会条件は、田中と働いたことがあること",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "魔王様も入るか？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……いや",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**会長を務めてやる**",
    "tags": [
     "sfx:ドンッ",
     "shake"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "うおおおおお！！",
    "tags": [
     "3人歓声"
    ],
    "mono": false,
    "group": true
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "なんで魔王が会長！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "20年分の議事録がある。この会で、私が一番長い",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "……全会一致で、承認します",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "……この会が承認を出すのは、これが初めてですね",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "承認とは、そういうものだ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "……ひとつ、よろしいですか",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "言え",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "どうせ転生するなら、勇者は高橋さんがよかったです",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "……高橋さん",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "営業で、あの人だけが仕様どおりに動いていました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "高橋さんとパーティーを組んで、冒険したかった",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え、俺じゃなくて！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "……はい",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "高橋君の経費精算は、いつも締め切り前に抜けもれなく申請されていたな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "……魔王様も、ご存じだったんですね",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "経理は、書類で人を覚える",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "……悪い職場では、なかったんですけどね",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "その『けどね』が痛い！",
    "tags": [],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S7.5",
  "title": "速射審査ラッシュ：細かい伝票の束（v2.0新設・裁定K）",
  "nodes": [
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "BGM:速い事務ロック",
     "テキスト送り:速",
     "tone:gag"
    ]
   },
   {
    "t": "dir",
    "raw": "▼仕様：細かい伝票7枚を1枚10〜20秒で連続処理。大ゴマなし・追加素材なし（立ち絵＋CSS書き文字のみ）。胃ゲージ対象外——誤判定でも胃は減らず、魔王の一言ツッコミ（本シーン末尾の表）が返って正しい判定へ進む（詰みなし）。"
   },
   {
    "t": "dir",
    "raw": "▼正解構成：承認が正解＝【速射2】と【速射5】。残り5枚は差し戻し。速射でも「全部差し戻せばいい」化を防ぐ。"
   },
   {
    "t": "dir",
    "raw": "▼演出：判定のたびにCSS書き文字（）を連打。3-3手法「テキスト送り:速」の最高速の見せ場。"
   },
   {
    "t": "dir",
    "raw": "▼自動セーブ復帰点：本シーン頭。"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……最後に、大物が残っているな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "その前だ。**この細かい束を、片付ける**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あ、それ軽いやつなんで、まとめてポンと",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**1枚ずつだ、田中**",
    "tags": [
     "sfx:バンッ"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "rush",
    "n": 1,
    "item": "串焼き　48本　4,800G"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "移動中の食料です！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼判断 【正解：差し戻し】"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**1日で48本は、業務ではない。食欲だ**。差し戻し",
    "tags": [
     "sfx:バン"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "育ち盛りなんで！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "30過ぎだ。前世を足せば50を超える",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "rush",
    "n": 2,
    "item": "砥石　3個　300G"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "剣の手入れ用です",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼判断 【正解：承認】（業務の消耗品・実費。線引き表「通る」区分）"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……通す。**普通の伝票は、普通に通る**",
    "tags": [
     "sfx:トン"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "なんか今、初めて社会に認められた気がする",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "rush",
    "n": 3,
    "item": "開運の壺　35,000G"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "旅の安全祈願です！　めっちゃ効くって言われて！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼判断 【正解：差し戻し】"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**その売り文句、前世の貴様だ**。差し戻し",
    "tags": [
     "sfx:バン"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……あー、言ってたかも",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "rush",
    "n": 4,
    "item": "ノルマン様うちわ　300本"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "ファンサービスです！　知名度も戦力のうち！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "在庫は",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "297本あります",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼判断 【正解：差し戻し】"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**3本しか出ていない**。差し戻し",
    "tags": [
     "sfx:バン"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "rush",
    "n": 5,
    "item": "回復薬　12本　1,200G"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "今度こそ、本物の回復薬です！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "在庫記録と、一致しています",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼判断 【正解：承認】（実数・単価・日付が記録と一致。線引き表「通る」区分）"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "実数、単価、日付。……**完璧だ**",
    "tags": [
     "sfx:トン"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "でしょ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**なぜ毎回できん**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "rush",
    "n": 6,
    "item": "サイン色紙　100枚"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "求められるんですよ、俺のサイン！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼判断 【正解：差し戻し】"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**書くべきは、伝票の訂正印だ**。差し戻し",
    "tags": [
     "sfx:バン"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "rush",
    "n": 7,
    "item": "『勇者のテーマ』作曲依頼費　80,000G"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "入場曲です！　士気が上がる！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "誰の",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "俺の",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼判断 【正解：差し戻し】"
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "差し戻し",
    "tags": [
     "sfx:バン",
     "即答"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "サビだけでも聴きます？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**聴かん**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "（遠くから）サビは、ちょっといいぞ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "でしょ！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**通らんものは、通らん**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "ラッシュ終了",
    "note": "",
    "tags": [
     "BGM:止む"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "以上。束の処理を終了する",
    "tags": [
     "sfx:トントン"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "7枚中、通ったのは2枚",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "打率で言えば2割8分！　悪くない！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "**8分6厘です**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "細かい！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……さて",
    "tags": [
     "tone:serious寄り",
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**残るは、この120万だけだ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……。",
    "tags": [
     "sfx:ゴク……"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "誤判定時の一言ツッコミ（胃は減らない・1枚ごと）",
    "note": "",
    "tags": []
   }
  ]
 },
 {
  "id": "S8",
  "title": "伝票5【ボス】：ドラゴン討伐費（実態は接待宴会＋私物混入の闇鍋）",
  "nodes": [
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "BGM:ボス戦（ただし事務的）"
    ]
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……最後の1枚です",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "ドラゴン討伐費。**120万ゴールド**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……120万",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "内訳を",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "討伐に伴う、諸経費です",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**諸経費という項目は、経理に存在しない**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "言い訳・第1段：討伐そのもの",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あのドラゴン、めちゃくちゃ強かったんですよ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "三日三晩、死闘でした！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼呼び出し：タクトの証言"
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**30分で終わったが？**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "タクト！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "あいつ、途中から寝てたぞ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "寝てない！　目を閉じて、戦況を読んでたんです！",
    "tags": [
     "v2.0増補"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**いびきの戦況があるか**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "言い訳・第2段：負傷者対応",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "い、いや！　討伐後の負傷者対応で費用が！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "治療費とか、宿泊とか、食事とか！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼呼び出し：カンバンの証言"
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "支出の記録があります",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "**酒類：68%。食事：22%。治療費：0%**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……治療費、ゼロ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "誰も、怪我をしていませんので",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "心の傷は！？",
    "tags": [
     "v2.0増補"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "**心療の領収書は、ありません**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**あっても、通るかは別だ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "言い訳・第3段：士気の維持",
    "note": "",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "それは……その、慰労も戦略のうちというか！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "士気の維持は、世界を救うために必要な投資で！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼呼び出し：ファルムの証言"
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "私は宴会で、**ドラゴンの中の人と名刺交換しました**",
    "tags": [
     "※秘密A・匂わせのみ"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "ファルム！！！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……その話は、後で聞く",
    "tags": [
     "※秘密A：ここで打ち切る。第1話では追及しない"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "内訳の底：混ざっていたもの",
    "note": "",
    "tags": [
     "tone:gag",
     "テキスト送り:速"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……この120万、まだ底がある",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "底の追加2件",
    "note": "（v2.0増補・線引き表「通らない」区分より）",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『宴会コンパニオン　手配料　60,000』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "盛り上げ要員です！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**討伐に、盛り上げ要員**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "士気が……その……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『祝勝花火　特大30発　90,000』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "勝利の狼煙です！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**狼煙は、1発だ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "30発は……",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**花火だ。差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『馬車修理代 18万』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "討伐で壊れて",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "**その日は、休養日です**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "行き先は、湖畔の保養地でした",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#2-3／やらかし回想",
     "モノクロ",
     "粗線"
    ]
   },
   {
    "t": "narr",
    "text": "回想：休養日の湖畔の保養地。馬車をぶつけて笑っているノルマン。",
    "tags": []
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "tone:gag"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……業務は",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "**してないです**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#3-3",
     "集中線",
     "sfx:ドンッ"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『宿の壁 修繕費 5万』**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "……それは、俺だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "酔って、壁を殴った",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**弁償は、その場で済ませた。俺の金でだ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……では、なぜ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**同じ壁の領収書が、この束の中にある**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "beat",
    "tags": [
     "全員がゆっくりノルマンを見る",
     "shake",
     "無言ビート"
    ],
    "text": ""
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……落ちてたので",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "**俺が払った領収書だろうが！！**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "魔王、底を打つ",
    "note": "",
    "tags": [
     "BGM:停止",
     "tone:serious",
     "明朝体",
     "テキスト送り:遅"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "田中",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "討伐は30分。宴会は朝まで",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "支出の7割が酒。治療費はゼロ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "休養日の馬車。他人が払った壁",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……**つまり、これは討伐費ではないな**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "dir",
    "raw": "▼プレイヤー判断（本作最大の見せ場）：差し戻し"
   },
   {
    "t": "dir",
    "raw": "根拠：カンバンの支出記録＋タクトの証言（討伐30分）"
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#3-5／本作最大のコマ",
     "集中線",
     "shake:強",
     "ズームイン",
     "sfx:ドンッ",
     "BGM:一撃"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "そのドラゴン討伐——",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**接待交際費で出してますよね？**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し！**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "うわあああああああ",
    "tags": [
     "崩れ落ちる",
     "shake"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#2-5／やらかし回想",
     "モノクロ",
     "粗線"
    ]
   },
   {
    "t": "narr",
    "text": "回想：宴会場。ドラゴンと肩を組み、ジョッキを掲げるノルマン。",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）いやー、今日はいい討伐でした！　お疲れさまでーす！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "extra",
    "name": "ドラゴン",
    "text": "（回想）こちらこそー",
    "tags": [
     "※秘密A・匂わせ"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "（回想）領収書、**討伐費で**お願いしまーす",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層",
    "tags": [
     "tone:gag"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "肩を組んでいるな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……仲良くなっちゃって",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "討伐とは",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……ノーコメントで",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……最後に言っておく",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**ドラゴンを倒した費用なら、私は120万でも通した**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "え",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**倒していないから、通らんのだ**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   }
  ]
 },
 {
  "id": "S9",
  "title": "エピローグ：始末書",
  "nodes": [
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#5／上コマ",
     "tone:gag"
    ]
   },
   {
    "t": "narr",
    "text": "机に向かい、始末書を書かされるノルマン。背後から3人が無言で見下ろしている。",
    "tags": []
   },
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／魔王城マップ",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "始末書だ。3枚書け",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "3枚！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "1枚は私に。1枚は経理に",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "1枚は、自分で読み返せ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……はい",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "字、きたねえな",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "日付が抜けています",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "再提出ですね",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "みんな厳しくない！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "決裁",
    "variant": "決裁層／不備の連鎖（テンポ重視・巻きで見せる）",
    "tags": [
     "tone:gag",
     "テキスト送り:速",
     "BGM:だんだん忙しなくなる"
    ]
   },
   {
    "t": "dir",
    "raw": "始末書を出す→不備→再提出、を短いカットで畳み掛ける。1往復1クリック。"
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "書けました！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "日付がない。**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "書けました！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "宛名が違う。**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "書けました！！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……印鑑が、逆さだ。**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "もう3回目ですよ！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "4回目だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "書けましたァ！！！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……この『反省』の欄",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**『次から気をつける』しか書いていない**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "気をつけますって！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "不備ループ延長戦",
    "note": "（v2.0増補）",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "書けましたァァ！！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……『始末書』が、**『始末所』**になっている",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "もう場所でいいでしょ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "書類は細部だ。**差し戻し**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "……見かねて、**テンプレートを作りました**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "有能！　最初から出してよ！",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "falm",
    "name": "ファルム",
    "text": "**前世で100枚書いた**ので、体が覚えていました",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "kanban",
    "name": "カンバン",
    "text": "紙の補充です。**あと30枚あります**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "そんなに間違えないよ！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "tact",
    "name": "タクト",
    "text": "（腕組みで）おら、書け書け",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "なんでみんな手際いいの！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "ミミックの追い打ち",
    "note": "",
    "tags": [
     "次回の燃料"
    ]
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "あ、そうだ課長！　領収書の一部、ミミックに食われたんですけど、それって——",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……。",
    "tags": [
     "無言ビート"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**差し戻し！**",
    "tags": [
     "sfx:ドンッ",
     "即答"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "食われたのに！？",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "食われる場所に置いた貴様の責任だ",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "魔王、ついに声を荒げる",
    "note": "",
    "tags": [
     "BGM:停止",
     "無言ビート",
     "tone:serious",
     "明朝体",
     "flash"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……田中",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "私は前世で、貴様の精算を20年待った",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "転生して、種族が変わって、魔王になって",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**それでもまだ、待たされている**",
    "tags": [
     "shake"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "漫画",
    "variant": "漫画層",
    "tags": [
     "大ゴマ#5／下コマ",
     "集中線",
     "shake:強",
     "sfx:ドオン"
    ]
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "**不 備 を な く せ ！！**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "layer",
    "layer": "RPG",
    "variant": "RPG層／魔王城・城門前（引きの画）",
    "tags": [
     "tone:gag",
     "BGM:とほほなBGM",
     "カメラ:遠景・キャラは小さく"
    ]
   },
   {
    "t": "narr",
    "text": "夕暮れ。城門から、書類の束を抱えたノルマンがとぼとぼ出ていく後ろ姿。",
    "tags": []
   },
   {
    "t": "narr",
    "text": "城のバルコニーに、腕を組んだ魔王の小さなシルエット。",
    "tags": []
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……もうこれくらい、通してよ……",
    "tags": [
     "小さい文字",
     "遠景のまま"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "narr",
    "text": "ノルマンの姿が、ゆっくり小さくなっていく。",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "（バルコニーから）**来月、また来い**",
    "tags": [],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "norman",
    "name": "ノルマン",
    "text": "……はーい",
    "tags": [
     "かすかに"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "mark",
    "label": "ラストの匂わせ",
    "note": "",
    "tags": [
     "※秘密A",
     "カメラが魔王の机へ戻る"
    ]
   },
   {
    "t": "narr",
    "text": "誰もいなくなった審査の間。魔王の机の隅、書類の束の一番下に、判の押された一冊が見えている。",
    "tags": []
   },
   {
    "t": "narr",
    "text": "『魔王国 興行収支報告書（極秘）』",
    "tags": []
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……あの男が、これに気づくのはいつになるか",
    "tags": [
     "tone:serious",
     "明朝体"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "line",
    "who": "maou",
    "name": "魔王",
    "text": "……まあ、精算が先だ",
    "tags": [
     "tone:gag",
     "老眼鏡を外す"
    ],
    "mono": false,
    "group": false
   },
   {
    "t": "theend"
   }
  ]
 }
];
window.RUSH_RETORT = {
 "1": "……48本を通しかけた。訂正する",
 "2": "待て。**これは通していい伝票だ**。珍しいが、ある",
 "3": "壺は通らん。**壺は、いつの世も通らん**",
 "4": "うちわは武具ではない。訂正する",
 "5": "……記録と合っている。**合っているものは、通す**",
 "6": "色紙で世界は救えん。訂正する",
 "7": "入場曲に8万は出さん。……サビも、だ"
};
window.REACTION = {
 "approve_wrong": {
  "norman": "あざす！　じゃあこれも通りますよね！？",
  "maou": "……待て。今、何を通した",
  "stomach": "−1"
 },
 "evidence_wrong": {
  "norman": "それ、今の話と関係なくないですか？",
  "maou": "……関係のない書類を突きつけた。私の落ち度だ",
  "stomach": "−1"
 },
 "witness_wrong": {
  "norman": "その人、その場にいませんでしたけど",
  "maou": "……確認不足だ",
  "stomach": "−1"
 },
 "reject_wrong": {
  "norman": "え、それもダメなんですか……",
  "maou": "……いや。今のは、通すべきだった",
  "stomach": "−1"
 },
 "rush_wrong": {
  "norman": "え、今のダメなの？",
  "maou": null,
  "stomach": "±0（胃ゲージ対象外）"
 },
 "gameover": {
  "norman": "やった！　全部通った！",
  "maou": "もういい……全額承認で……",
  "stomach": "—"
 },
 "gameover_caption": "本日の決裁は終了しました",
 "retry_line": "……いや。通していい額ではない",
 "gameover_sleep": [
  {
   "who": "norman",
   "name": "ノルマン",
   "text": "魔王様？　……あ、寝てる"
  },
  {
   "who": "norman",
   "name": "ノルマン",
   "text": "粘れば通る。やっぱ粘れば通るんすよ！"
  },
  {
   "who": "maou",
   "name": "魔王",
   "text": "……。"
  },
  {
   "who": "maou",
   "name": "魔王",
   "text": "……判は……そこに……"
  }
 ],
 "gameover_report": [
  "第一期　魔王国　決算報告",
  "勇者一行 経費申請　全件承認（差し戻し 〇件）",
  "年間予算 超過率　一二〇〇%",
  "魔王国 財政　破綻",
  "以上、報告いたします。"
 ],
 "gameover_telop": [
  "世界は荒廃した……",
  "GAME OVER"
 ],
 "gameover_revive": [
  {
   "who": "maou",
   "name": "魔王",
   "text": "……。"
  },
  {
   "who": "maou",
   "name": "魔王",
   "text": "……ああ、いつぞやもらった胃薬か"
  },
  {
   "who": "maou",
   "name": "魔王",
   "text": "……効くわけがない。気の持ちようだ"
  },
  {
   "who": "maou",
   "name": "魔王",
   "text": "いや、そんなことさせるわけにはいかん！"
  },
  {
   "who": "maou",
   "name": "魔王",
   "text": "……決裁を、続ける"
  }
 ],
 "gameover_buttons": [
  "続きから",
  "タイトルへ戻る"
 ]
};
window.CALL_CHAT = {
 "tact": [
  "俺に聞くな。俺は現場だ",
  "あいつの言うことは、6割盛られてる"
 ],
 "kanban": [
  "記録にないものは、なかったことです",
  "日付だけは、嘘をつきません"
 ],
 "falm": [
  "……仕様書がないので、答えられません",
  "口頭の指示は、証拠になりません"
 ]
};
window.CALL_BLOCK = [
 "おいおい、仲間だろ？",
 "そこは口裏合わせるとこでしょ！",
 "（小声）あとで奢るから"
];
window.HINT_LINE = {
 "hint_kanban": {
  "who": "kanban",
  "name": "カンバン",
  "text": "**先ほど申し上げた、記録です**"
 },
 "hint_falm": {
  "who": "falm",
  "name": "ファルム",
  "text": "**……お呼びいただけると、思っていました**"
 }
};
